//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjiznica2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prijava2
    {
        public string Korisnik { get; set; }
        public string Lozinka { get; set; }
    }
}
